### ISSUE TITLE
Improve main page load speed

### ISSUE THREAD

**Issue by SamSamskies** [realworldreact/reactathon-2018#38]
Implement lazy load for highlights images based on timer rather than scroll and maybe optimize images further. The quickest fix would be to remove some of the images.

**Comment by dunphyben** [comment]
For mobile optimization, we can probably leave out the `2017 Highlights` images + the `:hover` speaker images.

**Comment by SamSamskies** [comment]
Good call. That would speed up things a lot. Will need to implement mobile detection.
